### ISSUE TITLE
Save metadata on the same file, not in another

### ISSUE THREAD

**Issue by JosueChG** [mpatric/mp3agic#69]
Hi, I started editing the mp3 tags using mp3agic and it worked well.
But I am a little dissapointed that when the metadata is to be saved it has to go to a new file, not the same file.
I know that to save the edited tags in the same file is possible as VLC, Winamp and other programs do it. And I want the program I am doing to do it as well.
Is that possible using mp3agic? if not, can you suggest me another library that is able to do it?
I hope and thank your answers.

**Comment by ahristov314** [comment]
Of course it's NOT a OS restriction. It's just bad design : when writing the new mp3 file, the MPEG files are copied from the old file, (in the saveMpegFrames method ), so if both the new and the old file are the same, there's nowhere to read from because the file gets truncated on creation. A better approach would have been to read the frames in memory, THEN write the file. It's like we're talking about Gb-sized files.

**Comment by ahristov314** [comment]
What I don't understand is why the developer, knowing what the issue is, would blame it on the OS. 

Anyway, here's a fix. Took just one hour:

https://github.com/mpatric/mp3agic/pull/202
